server:
  port: 8081

spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/studentsconnect'
    username: root
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

server_value: blabla